version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000" #
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 app:app
