version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - minio
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app
